### ISSUE TITLE
该模块是否支持nginx 1.13以及openresty 1.13.6.1呢

### ISSUE THREAD

**Issue by saga1015** [hzarch/ngx_ssl_session_cache_module#1]
rt
京东的大拿们，请问是否支持上述nginx版本啊？

**Comment by shimengwang** [comment]
ngx_ssl_session_cache_module支持nginx 1.13。
nginx在1.9.14版本之后引入了OpenSSL的Async，只要满足nginx>1.9.14即可。

**Comment by saga1015** [comment]
@shimengwang 另外我源码目录下有patch，那在nginx 1.13上还需要打这个补丁吗？

**Comment by shimengwang** [comment]
@saga1015 需要打上nginx_1.12.0_ssl_session_cache.patch补丁

**Comment by saga1015** [comment]
@shimengwang 收到，感谢感谢 ：-）
